
# https://hub.docker.com/_/elasticsearch/
elasticsearch:
  image: elasticsearch:1.7.1
  ports:
   - "9200:9200"

# https://hub.docker.com/_/kibana/
kibana:
  image: kibana:4.1.2
  links:
   - elasticsearch
  ports:
   - "5601:5601"
